/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/iphone_14.glb 
Author: polyman (https://sketchfab.com/ely.haddad)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iphone-14-product-red-5g-6022f78c93664f9d9e67af0f8090ae68
Title: Iphone 14 Product Red 5G
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Iphone({ color, ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/iphone_14.glb");

  const coloredMaterial = new THREE.MeshStandardMaterial({
    color: color,
    metalness: 0.9,
    roughness: 1,
  });

  return (
    <group
      {...props}
      dispose={null}
    >
      <group
        scale={20}
        ref={group}
      >
        <mesh
          //backScreen
          geometry={nodes.eNsfTKiBnEXGdim.geometry}
          material={coloredMaterial}
        />

        <mesh
          //joints
          geometry={nodes.UnmZdJdOkcLkEPn.geometry}
          material={coloredMaterial}
        />
        <mesh
          //skeleton
          geometry={nodes.YAsjXBFyupscUHX.geometry}
          material={coloredMaterial}
        />
        <mesh
          //signal bar covering
          geometry={nodes.WlRuKutknUfoblK.geometry}
          material={coloredMaterial}
        />
        <mesh
          //signal bar inside
          geometry={nodes.KOlZzvoWenueVAg.geometry}
          material={coloredMaterial}
        />
        <mesh
          //signal bar edge
          geometry={nodes.SdtKuXLqrxLAtHF.geometry}
          material={coloredMaterial}
        />
        <mesh
          //camera lens 1
          geometry={nodes.rSFCqtTzcmZVmlh.geometry}
          material={coloredMaterial}
        />
        <mesh
          //camera lens 2
          geometry={nodes.rvsvilNSbcvpXxW.geometry}
          material={coloredMaterial}
        />
        <mesh
          //camera 3
          geometry={nodes.iRHBLeVtDyPtdwr.geometry}
          material={coloredMaterial}
        />
        <mesh
          //camera platform
          geometry={nodes.WoAwKqfldMagGNG.geometry}
          material={coloredMaterial}
        />
        <mesh
          //camera platform 2
          geometry={nodes.KsgmzJcyKwxKRNd.geometry}
          material={coloredMaterial}
        />
        <mesh
          //buttons
          geometry={nodes.LYSujqbJMAxqlak.geometry}
          material={coloredMaterial}
        />
        <mesh
          //buttons depth
          geometry={nodes.BqlEpmvnRttcNCp_0.geometry}
          material={coloredMaterial}
        />
        <mesh
          //logo
          geometry={nodes.jkbTFmXuEVLLYcD.geometry}
          material={coloredMaterial}
        />
        <mesh
          //charging port
          geometry={nodes.NdLWElWwVpppDFM.geometry}
          material={coloredMaterial}
        />
        <mesh
          //light edge
          geometry={nodes.qdQOhtwhgePMXqH.geometry}
          material={coloredMaterial}
        />
        <mesh
          //mute switch
          geometry={nodes.xJxwaVkTnmwRiAQ.geometry}
          material={coloredMaterial}
        />
        <mesh
          //buttons edge inside
          geometry={nodes.wMnQtLGqbklQtHv.geometry}
          material={coloredMaterial}
        />
        <mesh
          geometry={nodes.YcjvOazkmOSnTyy.geometry}
          material={materials.neaHdWdFdedPahd}
        />
        <mesh
          geometry={nodes.kmUbEpnCAMtGlMx.geometry}
          material={materials.OhTNHWsVNchlOwn}
        />
        <mesh
          geometry={nodes.DEOxAbabYvAEcIO.geometry}
          material={materials.IEwXfeCFbMdmcUa}
        />
        <mesh
          //main body black
          geometry={nodes.hZYUYnbwURyfKbh.geometry}
          material={materials.ttdgAkUgkHXHZGm}
        />
        <mesh
          geometry={nodes.OioPizonMnazBQa.geometry}
          material={materials.ttdgAkUgkHXHZGm}
        />
        <mesh
          //screen
          geometry={nodes.AuuOKcgUGrLfpna.geometry}
          material={materials.IuLMFuNDkMLMOHi}
        />
        <mesh
          geometry={nodes.KoYUqnVxexjDErM.geometry}
          material={materials.ttdgAkUgkHXHZGm}
        />
        <mesh
          geometry={nodes.zkygQIoQzNJKRKm.geometry}
          material={materials.zEaJDbAxpzOUMJk}
        />
        <mesh
          geometry={nodes.DCnQCVVyJnltxoT.geometry}
          material={materials.zvNmmOyIiqRbAKw}
        />
        <mesh
          geometry={nodes.bsHxLxJNOOkizTv.geometry}
          material={materials.ttdgAkUgkHXHZGm}
        />
        <mesh
          geometry={nodes.dcDYbuNpesslmEe.geometry}
          material={materials.ZwMswXBUQZQZmsX}
        />
        <mesh
          geometry={nodes.OZclzYurlldxUst.geometry}
          material={materials.TxyJXXacDyYiWoe}
        />
        <mesh
          geometry={nodes.odGFOpHkndvIAZh.geometry}
          material={materials.XkzgKvYcZKVbjge}
        />
        <mesh
          geometry={nodes.vrjCooqjKzjnnbL.geometry}
          material={materials.eEaJHFmLhwEzzNr}
        />
        <mesh
          geometry={nodes.BJetwTwvQRUbcuD.geometry}
          material={materials.FXJMnbSjSbAAevm}
        />
        <mesh
          geometry={nodes.LlqOTGugJLMBKsy.geometry}
          material={materials.zvNmmOyIiqRbAKw}
        />
        <mesh
          geometry={nodes.mCBtJXTLtctZXSr.geometry}
          material={materials.tASDVcXutCLTUaR}
        />
        <mesh
          geometry={nodes.LSeadyFauSFYcKt.geometry}
          material={materials.ttdgAkUgkHXHZGm}
        />
        <mesh
          geometry={nodes.YhFgSMLVnmWzNYE.geometry}
          material={materials.zEaJDbAxpzOUMJk}
        />
        <mesh
          geometry={nodes.ZsWROloKDPsGiTX.geometry}
          material={materials.nMOvQhJDZzMhgcC}
        />
        <mesh
          geometry={nodes.KoBDhufrVYDPenk.geometry}
          material={materials.qcMdePKFlQICygl}
        />
        <mesh
          geometry={nodes.LusuWTsDhpxislc.geometry}
          material={materials.ttdgAkUgkHXHZGm}
        />
        <mesh
          geometry={nodes.QtZQvXfRzMRcIkR.geometry}
          material={materials.rbDqRWICmEXCuPZ}
        />
        <mesh
          geometry={nodes.elABHtcbesdHjmY.geometry}
          material={materials.MeRJeoYxuDhgrgF}
        />
        <mesh
          geometry={nodes.lZiKavUGcvBhVpr.geometry}
          material={materials.MeRJeoYxuDhgrgF}
        />
        <mesh
          geometry={nodes.lSBPdHMDzVFdAdg.geometry}
          material={materials.OhTNHWsVNchlOwn}
        />
        <mesh
          geometry={nodes.XrOxpFZvHSkuyfE.geometry}
          material={materials.XkzgKvYcZKVbjge}
        />
        <mesh
          geometry={nodes.nBGQJHklmBPwcYS.geometry}
          material={materials.TxyJXXacDyYiWoe}
        />
        <mesh
          geometry={nodes.rGhuVHRLEFOyWae.geometry}
          material={materials.wGKUwFouJUDFXuG}
        />
        <mesh
          geometry={nodes.rqLPGxeRIYHeaht.geometry}
          material={materials.eEaJHFmLhwEzzNr}
        />
        <mesh
          geometry={nodes.wDlsjigbBiffkCL.geometry}
          material={materials.FQDpYcoZqQqygEk}
        />
        <mesh
          geometry={nodes.DSsnDcfMxdgDGLP.geometry}
          material={materials.NYAtGFztSwMRuMY}
        />
        <mesh
          geometry={nodes.ndGGzNvMtBJaSMo.geometry}
          material={materials.FXJMnbSjSbAAevm}
        />
        <mesh
          geometry={nodes.nkZiJbjNKamQWsp.geometry}
          material={materials.wGKUwFouJUDFXuG}
        />
        <mesh
          geometry={nodes.wCpqVrKFGxRddQy.geometry}
          material={materials.FQDpYcoZqQqygEk}
        />
        <mesh
          geometry={nodes.pVmOmLhHgtcanvX.geometry}
          material={materials.NYAtGFztSwMRuMY}
        />
        <mesh
          geometry={nodes.FkIeInEUTCyAciC.geometry}
          material={materials.XkzgKvYcZKVbjge}
        />
        <mesh
          geometry={nodes.mFREpdOoLsfeOec.geometry}
          material={materials.FXJMnbSjSbAAevm}
        />
        <mesh
          geometry={nodes.NIVUzTiVuoibcgX.geometry}
          material={materials.eEaJHFmLhwEzzNr}
        />
        <mesh
          geometry={nodes.jXLhZQkHqWEJCVz.geometry}
          material={materials.yhIqKVKwwbwlcZM}
        />
        <mesh
          geometry={nodes.odXJvopUWpeJOmT.geometry}
          material={materials.ptAGeWmAEdSxVsp}
        />
        <mesh
          geometry={nodes.NKNfSyChAcNaVdP.geometry}
          material={materials.PthbyWpJDVwTnlJ}
        />
        <mesh
          geometry={nodes.KwpcZHizufsYCCi.geometry}
          material={materials.PpCORwuqBePvnQo}
        />
        <mesh
          geometry={nodes.KfGAmcLebwxnsLY.geometry}
          material={materials.UPHuViOGMaoonhR}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/iphone_14.glb");
